export enum MutationKey {
  /** Auth */
  SIGN_UP_WITH_EMAIL = "SIGN_UP_WITH_EMAIL",
  SIGN_IN_WITH_EMAIL = "SIGN_IN_WITH_EMAIL",
  FORGOT_PASSWORD = "FORGOT_PASSWORD",
  RESET_PASSWORD_REQUEST = "RESET_PASSWORD_REQUEST",
  VERIFY_RESET_CODE = "VERIFY_RESET_CODE",
  RESET_PASSWORD = "RESET_PASSWORD",
  
  /** User */
  COMPLETE_REGISTRATION = "COMPLETE_REGISTRATION",
}
